### ISSUE TITLE
packit-prod: get PR ended with 404

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#128]
```
[2019-09-11 09:21:50,907: INFO/ForkPoolWorker-1] Github issue 330 comment event.
[2019-09-11 09:21:50,908: INFO/ForkPoolWorker-1] Target repo: rpm-software-management/mock.
[2019-09-11 09:21:53,633: ERROR/ForkPoolWorker-1] Task task.steve_jobs.process_message[41ece6ab-1551-4e36-9fcb-ceb45cbcb514] raised unexpected: UnknownObjectException(404, {
'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/pulls/#get-a-single-pull-request'})
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/tasks.py", line 42, in process_message
    return SteveJobs().process_message(event=event, topic=topic)
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 236, in process_message
    jobs_results = self.process_jobs(event_object)
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 86, in process_jobs
    package_config = event.get_package_config()
  File "/usr/local/lib/python3.7/site-packages/packit_service/service/events.py", line 282, in get_package_config
    self.base_ref = self.get_project().get_pr_info(self.issue_id).source_branch
  File "/usr/local/lib/python3.7/site-packages/ogr/services/github.py", line 478, in get_pr_info
    pr = self.github_repo.get_pull(number=pr_id)
  File "/usr/lib/python3.7/site-packages/github/Repository.py", line 2253, in get_pull
    self.url + "/pulls/" + str(number)
  File "/usr/lib/python3.7/site-packages/github/Requester.py", line 276, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/lib/python3.7/site-packages/github/Requester.py", line 287, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/pulls/#get-a-single-pull-request'}
```

I don't know, is this an issue or a race?

**Comment by lachmanfrantisek** [comment]
This line looks bad to me:
```
self.get_project().get_pr_info(self.issue_id).source_branch
```

It is `IssueCommentEvent` so there is no branch we can work with.

(Reason for the traceback: We are trying to get pull-quest with the number equal to the issue number.)

I am not sure, but we can fix that by simply removing lines 281-282?
