### ISSUE TITLE
packit-service-fedmsg:  The 'pyasn1<0.5.0,>=0.4.6' distribution was not found

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#131]
```
Traceback (most recent call last):
--
  | File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 578, in _build_master
  | ws.require(__requires__)
  | File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 895, in require
  | needed = self.resolve(parse_requirements(requirements))
  | File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
  | raise VersionConflict(dist, req).with_context(dependent_req)
  | pkg_resources.ContextualVersionConflict: (pyasn1 0.3.7 (/usr/lib/python3.7/site-packages), Requirement.parse('pyasn1<0.5.0,>=0.4.6'), {'pyasn1-modules'})
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/usr/local/bin/packit-service", line 6, in <module>
  | from pkg_resources import load_entry_point
  | File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3112, in <module>
  | @_call_aside
  | File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3096, in _call_aside
  | f(*args, **kwargs)
  | File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3125, in _initialize_master_working_set
  | working_set = WorkingSet._build_master()
  | File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 580, in _build_master
  | return cls._build_from_requirements(__requires__)
  | File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 593, in _build_from_requirements
  | dists = ws.resolve(reqs, Environment())
  | File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 781, in resolve
  | raise DistributionNotFound(req, requirers)
  | pkg_resources.DistributionNotFound: The 'pyasn1<0.5.0,>=0.4.6' distribution was not found and is required by pyasn1-modules
```

**Comment by jpopelka** [comment]
Reproducer:
```
$ docker run --rm -ti fedora:29 bash -c "dnf install -y python3-pyasn1; pip3 install google-auth"
...
Installed:
  python3-pyasn1-0.3.7-4.fc29.noarch
...
Collecting pyasn1-modules>=0.2.1 (from google-auth)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/lib/python3.7/site-packages (from rsa>=3.1.4->google-auth) (0.3.7)
pyasn1-modules 0.2.6 has requirement pyasn1<0.5.0,>=0.4.6, but you'll have pyasn1 0.3.7 which is incompatible.
Successfully installed google-auth-1.6.3 pyasn1-modules-0.2.6
```
which says:
- dnf install `pyasn1-0.3.7`
- pip install `pyasn1-modules-0.2.6` - pip knows that it requires `pyasn1>=0.4.6`, but **does NOT** update the `pyasn1` version 

When I pip install `pyasn1-modules-0.2.6` directly (not as a dep of something else), it works (pyasn1 is updated) ok:
```
$ docker run --rm -ti fedora:29 bash -c "dnf install -y python3-pyasn1; pip3 install `pyasn1-modules`"
Installed:
  python3-pyasn1-0.3.7-4.fc29.noarch
...
Successfully installed pyasn1-0.4.7 pyasn1-modules-0.2.6
```

**Comment by jpopelka** [comment]
Found [this](https://blog.softhints.com/python-dependency-error-modules-has-requirement-which-is-incompatible/) but it doesn't explain why it works the way it is.

**Comment by TomasTomecek** [comment]
Is this solved now?

**Comment by jpopelka** [comment]
Once #147 is merged.
