### ISSUE TITLE
The config file for packit not found in the packit-service repo after posting copr build comment.

### ISSUE THREAD

**Issue by rpitonak** [packit-service/packit-service#165]
```
2019-10-11 08:52:30,521: INFO/ForkPoolWorker-1] GitHub PR#164 comment event. Action: created.
--
  | [2019-10-11 08:52:30,522: INFO/ForkPoolWorker-1] Target repo: packit-service/packit-service.
  | [2019-10-11 08:52:32,881: DEBUG/ForkPoolWorker-1] The config file '.packit.yaml' not found on ref 'e8760ec6ac84ffabdf14c4275719c756b408e2c9' of the packit-service/packit-service repository.FileNotFoundError("File '.packit.yaml' on e8760ec6ac84ffabdf14c4275719c756b408e2c9 not found", UnknownObjectException(404, {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/contents/#get-contents' }))
  | [2019-10-11 08:52:33,062: DEBUG/ForkPoolWorker-1] The config file '.packit.yml' not found on ref 'e8760ec6ac84ffabdf14c4275719c756b408e2c9' of the packit-service/packit-service repository.FileNotFoundError("File '.packit.yml' on e8760ec6ac84ffabdf14c4275719c756b408e2c9 not found", UnknownObjectException(404, {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/contents/#get-contents' }))
  | [2019-10-11 08:52:33,325: DEBUG/ForkPoolWorker-1] The config file '.packit.json' not found on ref 'e8760ec6ac84ffabdf14c4275719c756b408e2c9' of the packit-service/packit-service repository.FileNotFoundError("File '.packit.json' on e8760ec6ac84ffabdf14c4275719c756b408e2c9 not found", UnknownObjectException(404, {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/contents/#get-contents' }))
  | [2019-10-11 08:52:33,515: DEBUG/ForkPoolWorker-1] The config file 'packit.yaml' not found on ref 'e8760ec6ac84ffabdf14c4275719c756b408e2c9' of the packit-service/packit-service repository.FileNotFoundError("File 'packit.yaml' on e8760ec6ac84ffabdf14c4275719c756b408e2c9 not found", UnknownObjectException(404, {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/contents/#get-contents' }))
  | [2019-10-11 08:52:33,686: DEBUG/ForkPoolWorker-1] The config file 'packit.yml' not found on ref 'e8760ec6ac84ffabdf14c4275719c756b408e2c9' of the packit-service/packit-service repository.FileNotFoundError("File 'packit.yml' on e8760ec6ac84ffabdf14c4275719c756b408e2c9 not found", UnknownObjectException(404, {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/contents/#get-contents' }))
  | [2019-10-11 08:52:33,856: DEBUG/ForkPoolWorker-1] The config file 'packit.json' not found on ref 'e8760ec6ac84ffabdf14c4275719c756b408e2c9' of the packit-service/packit-service repository.FileNotFoundError("File 'packit.json' on e8760ec6ac84ffabdf14c4275719c756b408e2c9 not found", UnknownObjectException(404, {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/contents/#get-contents' }))
  | [2019-10-11 08:52:33,867: ERROR/ForkPoolWorker-1] Task task.steve_jobs.process_message[7394cec7-68d9-4248-9555-571997520545] raised unexpected: AttributeError("'NoneType' object has no attribute 'upstream_project_url'")
  | Traceback (most recent call last):
  | File "/usr/lib/python3.7/site-packages/celery/app/trace.py", line 382, in trace_task
  | R = retval = fun(*args, **kwargs)
  | File "/usr/lib/python3.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
  | return self.run(*args, **kwargs)
  | File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 155, in _inner
  | reraise(*exc_info)
  | File "/usr/local/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 57, in reraise
  | raise value
  | File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 150, in _inner
  | return f(*args, **kwargs)
  | File "/usr/local/lib/python3.7/site-packages/packit_service/worker/tasks.py", line 47, in process_message
  | return SteveJobs().process_message(event=event, topic=topic)
  | File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 247, in process_message
  | ] = self.process_comment_jobs(event_object)
  | File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 175, in process_comment_jobs
  | handler = handler_kls(self.config, event)
  | File "/usr/local/lib/python3.7/site-packages/packit_service/worker/github_handlers.py", line 444, in __init__
  | self.package_config.upstream_project_url = event.project_url
  | AttributeError: 'NoneType' object has no attribute 'upstream_project_url'
```

**Comment by rpitonak** [comment]
Ahh, no I have just realized that we don't build packit-service in copr 🤦‍♂️
