### ISSUE TITLE
[Errno 21] Is a directory: '/sandcastle/sources'

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#314]
- https://sentry.io/organizations/red-hat-0p/issues/1422284472
- https://github.com/osbuild/osbuild/pull/199

**Comment by TomasTomecek** [comment]
any chance this is gonna be solved by the fixes which came in recently?

**Comment by jpopelka** [comment]
negative, sir, another one just came in: https://sentry.io/organizations/red-hat-0p/issues/1426674268

**Comment by TomasTomecek** [comment]
I can reproduce with vanilla packit:
```
09:09:40.624 upstream.py       DEBUG  new %autosetup line:
%autosetup -n osbuild-7.41.g6a14ba4
ERROR    Preparing of the upstream to the SRPM build failed: [Errno 21] Is a directory: '/home/tt/g/osbuild/osbuild/sources'
Traceback (most recent call last):
  File "/home/tt/g/user-cont/packit/packit/api.py", line 472, in create_srpm
    self.up.prepare_upstream_for_srpm_creation(upstream_ref=upstream_ref)
  File "/home/tt/g/user-cont/packit/packit/upstream.py", line 656, in prepare_upstream_for_srpm_creation
    self.specfile.download_remote_sources()
  File "/usr/lib/python3.7/site-packages/rebasehelper/specfile.py", line 143, in download_remote_sources
    LookasideCacheHelper.download('fedpkg', os.path.dirname(self.path), self.header.name, self.sources_location)
  File "/usr/lib/python3.7/site-packages/rebasehelper/helpers/lookaside_cache_helper.py", line 125, in download
    for source in cls._read_sources(basepath):
  File "/usr/lib/python3.7/site-packages/rebasehelper/helpers/lookaside_cache_helper.py", line 65, in _read_sources
    with open(path, 'r') as f:
IsADirectoryError: [Errno 21] Is a directory: '/home/tt/g/osbuild/osbuild/sources'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tt/g/user-cont/packit/packit/cli/utils.py", line 61, in covered_func
    func(config=config, *args, **kwargs)
  File "/home/tt/g/user-cont/packit/packit/cli/srpm.py", line 75, in srpm
    srpm_path = api.create_srpm(output_file=output, upstream_ref=upstream_ref)
  File "/home/tt/g/user-cont/packit/packit/api.py", line 476, in create_srpm
    ) from ex
packit.exceptions.PackitSRPMException: Preparing of the upstream to the SRPM build failed: [Errno 21] Is a directory: '/home/tt/g/osbuild/osbuild/sources'
```

**Comment by TomasTomecek** [comment]
The problem is that rebase-helper thinks that the osbuild upstream repo is a dist-git repo, because path "sources" exists - but in dist-git it's meant to be a file, while here it's a directory - hence the error message.
