### ISSUE TITLE
Set check on PR instead of traceback when user is not whitelisted

### ISSUE THREAD

**Issue by rpitonak** [packit-service/packit-service#32]
Right now when jobs cannot be executed, because of not approved account on the whitelist, packit service tracebacks:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/tasks.py", line 31, in process_message
    return SteveJobs().process_message(event=event, topic=topic)
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 375, in process_message
    raise PackitException(task_results)
packit.exceptions.PackitException: {'jobs': {'copr_build': {'success': False, 'details': {'msg': 'Account is not whitelisted!'}}}, 'project': 'packit-service/hello-world', '
trigger': 'pull_request'}
```

**Comment by TomasTomecek** [comment]
Would be nice to have this done in next few days when people start using the service.
