### ISSUE TITLE
TypeError: Object of type TestResult is not JSON serializable

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#380]
Probably caused by #364 and/or #365 

```

Task task.steve_jobs.process_message[1d82072b-5278-4158-8591-2b0e67015a8b] raised unexpected: EncodeError(TypeError('Object of type TestResult is not JSON serializable'))
--
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
  | yield
  | File "/usr/local/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
  | payload = encoder(data)
  | File "/usr/local/lib/python3.7/site-packages/kombu/utils/json.py", line 70, in dumps
  | **dict(default_kwargs, **kwargs))
  | File "/usr/lib64/python3.7/site-packages/simplejson/__init__.py", line 399, in dumps
  | **kw).encode(obj)
  | File "/usr/lib64/python3.7/site-packages/simplejson/encoder.py", line 296, in encode
  | chunks = self.iterencode(o, _one_shot=True)
  | File "/usr/lib64/python3.7/site-packages/simplejson/encoder.py", line 378, in iterencode
  | return _iterencode(o, 0)
  | File "/usr/local/lib/python3.7/site-packages/kombu/utils/json.py", line 59, in default
  | return super(JSONEncoder, self).default(o)
  | File "/usr/lib64/python3.7/site-packages/simplejson/encoder.py", line 273, in default
  | o.__class__.__name__)
  | TypeError: Object of type TestResult is not JSON serializable
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 449, in trace_task
  | uuid, retval, task_request, publish_result,
  | File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 149, in mark_as_done
  | self.store_result(task_id, result, state, request=request)
  | File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 407, in store_result
  | request=request, **kwargs)
  | File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 758, in _store_result
  | self.set(self.get_key_for_task(task_id), self.encode(meta))
  | File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 310, in encode
  | _, _, payload = self._encode(data)
  | File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 314, in _encode
  | return dumps(data, serializer=self.serializer)
  | File "/usr/local/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
  | payload = encoder(data)
  | File "/usr/lib64/python3.7/contextlib.py", line 130, in __exit__
  | self.gen.throw(type, value, traceback)
  | File "/usr/local/lib/python3.7/site-packages/kombu/serialization.py", line 54, in _reraise_errors
  | reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  | File "/usr/local/lib/python3.7/site-packages/vine/five.py", line 194, in reraise
  | raise value.with_traceback(tb)
  | File "/usr/local/lib/python3.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
  | yield
  | File "/usr/local/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
  | payload = encoder(data)
  | File "/usr/local/lib/python3.7/site-packages/kombu/utils/json.py", line 70, in dumps
  | **dict(default_kwargs, **kwargs))
  | File "/usr/lib64/python3.7/site-packages/simplejson/__init__.py", line 399, in dumps
  | **kw).encode(obj)
  | File "/usr/lib64/python3.7/site-packages/simplejson/encoder.py", line 296, in encode
  | chunks = self.iterencode(o, _one_shot=True)
  | File "/usr/lib64/python3.7/site-packages/simplejson/encoder.py", line 378, in iterencode
  | return _iterencode(o, 0)
  | File "/usr/local/lib/python3.7/site-packages/kombu/utils/json.py", line 59, in default
  | return super(JSONEncoder, self).default(o)
  | File "/usr/lib64/python3.7/site-packages/simplejson/encoder.py", line 273, in default
  | o.__class__.__name__)
  | kombu.exceptions.EncodeError: Object of type TestResult is not JSON serializable

```

**Comment by jpopelka** [comment]
We could probably make the `TestResult` JSON serializable, but I'm just wondering why we didn't see this before.
Do we now return the `TestResult` somewhere so that celery tries to store that in a backend?

**Comment by lachmanfrantisek** [comment]
> We could probably make the `TestResult` JSON serializable, but I'm just wondering why we didn't see this before.

The parsing and usage is quite new: #365
