### ISSUE TITLE
service config schema validation error

### ISSUE THREAD

**Issue by rishavanand** [packit-service/packit-service#552]
After upstream pull I get this error while using the github `files/scripts/webhook.py` script. I've even tried with freshly built docker images. It used to work before my today's pull & merge. The same secrets were working before. I've been using [this method](https://github.com/packit-service/deployment/pull/74) to generate local secrets. 

**command used:**
```
GITHUB_TOKEN=xxxxxxxx python3 files/scripts/webhook.py rishavanand/hello-world --pr 1
```

**logs from `packit-service` container:**
```
mod_wsgi (pid=26): Failed to exec Python script file '/usr/share/packit/packit.wsgi'.
[Sat Apr 11 13:47:07.453357 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826] mod_wsgi (pid=26): Exception occurred processing WSGI script '/usr/share/packit/packit.wsgi'.
[Sat Apr 11 13:47:07.465705 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826] Traceback (most recent call last):
[Sat Apr 11 13:47:07.465755 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826]   File "/usr/share/packit/packit.wsgi", line 1, in <module>
[Sat Apr 11 13:47:07.465760 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826]     from packit_service.service.app import application
[Sat Apr 11 13:47:07.465764 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826]   File "/usr/local/lib/python3.7/site-packages/packit_service/service/app.py", line 32, in <module>
[Sat Apr 11 13:47:07.465766 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826]     from packit_service.service.api import blueprint
[Sat Apr 11 13:47:07.465769 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826]   File "/usr/local/lib/python3.7/site-packages/packit_service/service/api/__init__.py", line 33, in <module>
[Sat Apr 11 13:47:07.465771 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826]     from packit_service.service.api.testing_farm import ns as testing_farm_ns
[Sat Apr 11 13:47:07.465774 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826]   File "/usr/local/lib/python3.7/site-packages/packit_service/service/api/testing_farm.py", line 39, in <module>
[Sat Apr 11 13:47:07.465776 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826]     config = ServiceConfig.get_service_config()
[Sat Apr 11 13:47:07.465779 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826]   File "/usr/local/lib/python3.7/site-packages/packit_service/config.py", line 143, in get_service_config
[Sat Apr 11 13:47:07.465781 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826]     cls.service_config = ServiceConfig.get_from_dict(raw_dict=loaded_config)
[Sat Apr 11 13:47:07.465784 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826]   File "/usr/local/lib/python3.7/site-packages/packit_service/config.py", line 105, in get_from_dict
[Sat Apr 11 13:47:07.465786 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826]     config = ServiceConfigSchema().load(raw_dict)
[Sat Apr 11 13:47:07.465789 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826]   File "/usr/local/lib/python3.7/site-packages/packit/schema.py", line 167, in load
[Sat Apr 11 13:47:07.465791 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826]     result = super().load(*args, **kwargs)
[Sat Apr 11 13:47:07.465794 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826]   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 723, in load
[Sat Apr 11 13:47:07.465798 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826]     data, many=many, partial=partial, unknown=unknown, postprocess=True
[Sat Apr 11 13:47:07.465802 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826]   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 904, in _do_load
[Sat Apr 11 13:47:07.465804 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826]     raise exc
[Sat Apr 11 13:47:07.465821 2020] [wsgi:error] [pid 26:tid 140076700710656] [client 172.18.0.1:55826] marshmallow.exceptions.ValidationError: {'fas_passwd': ['Unknown field.'], 'routing_keys': ['Unknown field.'], 'queue_name': ['Unknown field.']}
172.18.0.1 - - [11/Apr/2020:13:47:06 +0000] "POST /api/webhooks/github HTTP/1.1" 500 538
```

**webhook script response:**
the generated JSON along with the error below,
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 user-cont-team@redhat.com to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
```

can it be due to #538 ?
or is there some mistake on my end?

**Comment by jpopelka** [comment]
Yes, it's most likely caused by the #538.

I quickly grepped the code and I'm not sure where those unknown keys come from, I can see them only in [deployment/secrets/template/packit-service.yaml](https://github.com/packit-service/deployment/blob/master/secrets/template/packit-service.yaml#L29).
I have no idea why are they actually there - those are the fedora-messaging config keys and as such, should be specified in [fedora.toml](https://github.com/packit-service/deployment/blob/master/secrets/template/fedora.toml) and not in `packit-service.yaml`.
It needs more investigation - I'll take a look next week - or you're welcome to try too if you desperately need it now.

**Comment by rishavanand** [comment]
Thanks, simple removing those fields resolved the issue. 
I'll keep looking and let you know if I find anything that says why those fields are needed in `packit-service.yaml`

**Comment by jpopelka** [comment]
Please check whether packit-service/deployment#76 fixes it and close this if so. Thanks!

**Comment by rishavanand** [comment]
Yes, it's been been fixed 😄 
Thanks!
