### ISSUE TITLE
propose update fails with "TypeError: argument of type 'NoneType' is not iterable"

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#557]
```
Traceback (most recent call last):
 File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
   R = retval = fun(*args, **kwargs)
 File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
   return self.run(*args, **kwargs)
 File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 169, in _inner
   reraise(*exc_info)
 File "/usr/local/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 57, in reraise
   raise value
 File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 164, in _inner
   return f(*args, **kwargs)
 File "/usr/local/lib/python3.7/site-packages/packit_service/worker/tasks.py", line 55, in process_message
   task_results: dict = SteveJobs().process_message(event=event, topic=topic)
 File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 329, in process_message
   jobs_results[job_type] = self.process_comment_jobs(event_object)
 File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 273, in process_comment_jobs
   return handler_instance.run_n_clean()
 File "/usr/local/lib/python3.7/site-packages/packit_service/worker/handlers/abstract.py", line 109, in run_n_clean
   return self.run()
 File "/usr/local/lib/python3.7/site-packages/packit_service/worker/handlers/github_handlers.py", line 728, in run
   for branch in self.dist_git_branches_to_sync:
 File "/usr/local/lib/python3.7/site-packages/packit_service/worker/handlers/github_handlers.py", line 698, in dist_git_branches_to_sync
   return list(get_branches(*configured_branches))
 File "/usr/local/lib/python3.7/site-packages/packit/config/aliases.py", line 120, in get_branches
   if "rawhide" in sys_and_version:
TypeError: argument of type 'NoneType' is not iterable
```

- https://github.com/packit-service/packit/issues/793
- https://sentry.io/organizations/red-hat-0p/issues/1598842132

**Comment by jpopelka** [comment]
This applies only to packit (which has `dist_git_branch` instead of now deprecated `dist-git-branch`) and will be resolved once #548 gets deployed into production.
