### ISSUE TITLE
Copr config exception

### ISSUE THREAD

**Issue by rpitonak** [packit-service/packit-service#58]
I have been testing a new version of packit-service (master) on the stg today and I got this exception when `synchronize` event came.

```

[2019-07-23 11:50:58,899: ERROR/ForkPoolWorker-1] Task task.steve_jobs.process_message[a3f5fbaa-2654-4d94-b0ec-7525ec06e89c] raised unexpected: CoprConfigException("File contains no section headers.\nfile: '/opt/app-root/src/.config/copr', line: 1\n'FIXME'")
--
  | Traceback (most recent call last):
  | File "/usr/lib/python3.7/site-packages/copr/v3/helpers.py", line 22, in config_from_file
  | exists = raw_config.read(path)
  | File "/usr/lib64/python3.7/configparser.py", line 696, in read
  | self._read(fp, filename)
  | File "/usr/lib64/python3.7/configparser.py", line 1079, in _read
  | raise MissingSectionHeaderError(fpname, lineno, line)
  | configparser.MissingSectionHeaderError: File contains no section headers.
  | file: '/opt/app-root/src/.config/copr', line: 1
  | 'FIXME'
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
  | R = retval = fun(*args, **kwargs)
  | File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
  | return self.run(*args, **kwargs)
  | File "/usr/local/lib/python3.7/site-packages/packit_service/worker/tasks.py", line 31, in process_message
  | return SteveJobs().process_message(event=event, topic=topic)
  | File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 113, in process_message
  | jobs_results = self.process_jobs(event_object)
  | File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 79, in process_jobs
  | handlers_results[job.job.value] = handler.run()
  | File "/usr/local/lib/python3.7/site-packages/packit_service/worker/github_handlers.py", line 300, in run
  | return self.handle_pull_request()
  | File "/usr/local/lib/python3.7/site-packages/packit_service/worker/github_handlers.py", line 239, in handle_pull_request
  | owner = self.job.metadata.get("owner") or self.api.copr.config.get("username")
  | File "/usr/local/lib/python3.7/site-packages/packit/api.py", line 87, in copr
  | self._copr = CoprClient.create_from_config_file()
  | File "/usr/lib/python3.7/site-packages/copr/v3/client.py", line 24, in create_from_config_file
  | config = config_from_file(path)
  | File "/usr/lib/python3.7/site-packages/copr/v3/helpers.py", line 24, in config_from_file
  | raise CoprConfigException(str(ex))
  | copr.v3.exceptions.CoprConfigException: File contains no section headers.
  | file: '/opt/app-root/src/.config/copr', line: 1
  | 'FIXME'
```

**Comment by TomasTomecek** [comment]
do we actually have a stg copr config?

**Comment by rpitonak** [comment]
> do we actually have a stg copr config?

Now I can see that we don't have. What is the process there to get one?

**Comment by TomasTomecek** [comment]
I would just cp/symlink the prod one.
