### ISSUE TITLE
whitelist: release events check repo name instead of namespace

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#62]
I had to whitelist `ogr`; `packit-service` wasn't good enough. Is this expected?
```
[2019-07-29 06:52:59,741: ERROR/ForkPoolWorker-1] Task task.steve_jobs.process_message[c1dad33b-29fa-4ab6-a027-e2376835e407] raised unexpected: PackitException({'jobs': {'pr
opose_downstream': {'success': False, 'details': {'msg': 'Account is not whitelisted!'}}}, 'event': {'trigger': 'JobTriggerType.release', 'repo_namespace': 'packit-service',
 'repo_name': 'ogr', 'tag_name': '0.6.0', 'https_url': 'https://github.com/packit-service/ogr'}, 'trigger': 'JobTriggerType.release'})                                       
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task                                                                                 
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__                                                                         
    return self.run(*args, **kwargs)    
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/tasks.py", line 36, in process_message                                                                  
    return SteveJobs().process_message(event=event, topic=topic)                      
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 123, in process_message                                                                  
    raise PackitException(task_results) 
packit.exceptions.PackitException: {'jobs': {'propose_downstream': {'success': False, 'details': {'msg': 'Account is not whitelisted!'}}}, 'event': {'trigger': 'JobTriggerTy
pe.release', 'repo_namespace': 'packit-service', 'repo_name': 'ogr', 'tag_name': '0.6.0', 'https_url': 'https://github.com/packit-service/ogr'}, 'trigger': 'JobTriggerType.r
elease'}
```

**Comment by rpitonak** [comment]
Not expected, it is a bug.
