### ISSUE TITLE
running `/packit propose-update` results in traceback: AssertionError

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#639]
...and sentry didn't catch this :/

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 169, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 164, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/tasks.py", line 66, in process_message
    event=event, topic=topic, source=source
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 346, in process_message
    jobs_results[job_type] = self.process_comment_jobs(event_object)
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 275, in process_comment_jobs
    return handler_instance.run_n_clean()
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/handlers/abstract.py", line 109, in run_n_clean
    return self.run()
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/handlers/github_handlers.py", line 555, in run
    package_config=self.event.package_config,
  File "/usr/local/lib/python3.7/site-packages/packit_service/service/events.py", line 238, in package_config
    self._package_config = self.get_package_config()
  File "/usr/local/lib/python3.7/site-packages/packit_service/service/events.py", line 281, in get_package_config
    spec_file_path=spec_path,
  File "/usr/local/lib/python3.7/site-packages/packit_service/config.py", line 166, in get_package_config_from_repo
    spec_file_path=spec_file_path,
  File "/usr/local/lib/python3.7/site-packages/packit/config/package_config.py", line 313, in get_package_config_from_repo
    path=config_file_name, ref=ref
  File "/usr/local/lib/python3.7/site-packages/ogr/services/github/project.py", line 426, in get_file_content
    path=path, ref=ref
  File "/usr/lib/python3.7/site-packages/github/Repository.py", line 1504, in get_contents
    assert ref is github.GithubObject.NotSet or isinstance(ref, str), ref
AssertionError: None
```

**Comment by lbarcziova** [comment]
This should be fixed by #736
