### ISSUE TITLE
fedpkg still can't clone using auth a dist-git repo

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#93]
```
[2019-08-26 06:19:54,504: DEBUG/ForkPoolWorker-1] cmd = 'fedpkg --user packit -q clone packit /tmp/packit-dist-gitbbtanuot'
[2019-08-26 06:19:56,652: DEBUG/ForkPoolWorker-1]
[2019-08-26 06:19:56,653: ERROR/ForkPoolWorker-1] No user exists for uid 1012120000
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Could not execute clone: Failed to execute command.

[2019-08-26 06:19:56,653: ERROR/ForkPoolWorker-1] Command ['fedpkg', '--user', 'packit', '-q', 'clone', 'packit', '/tmp/packit-dist-gitbbtanuot'] failed
[2019-08-26 06:19:56,653: ERROR/ForkPoolWorker-1] Command ['fedpkg', '--user', 'packit', '-q', 'clone', 'packit', '/tmp/packit-dist-gitbbtanuot'] failed.
[2019-08-26 06:19:56,653: INFO/ForkPoolWorker-1] cleaning up the mess
[2019-08-26 06:19:56,653: DEBUG/ForkPoolWorker-1] Initialize kubernetes client
[2019-08-26 06:19:56,653: INFO/ForkPoolWorker-1] loading incluster config
[2019-08-26 06:19:56,685: INFO/ForkPoolWorker-1] removing sandbox pod
[2019-08-26 06:19:56,715: DEBUG/ForkPoolWorker-1] (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-store', 'Content-Type': 'application/json', 'Date': 'Mon, 26 Aug 2019 06:19:56 GMT', 'Content-Length': '270'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"docker-io-usercont-sandcastle-20190826-061956653569\" not found","reason":"NotFound","details":{"name":"docker-io-usercont-sandcastle-20190826-061956653569","kind":"pods"},"code":404}


[2019-08-26 06:19:56,715: DEBUG/ForkPoolWorker-1] remove contents of the PV
[2019-08-26 06:19:56,715: INFO/ForkPoolWorker-1] volume was not empty
[2019-08-26 06:19:56,716: DEBUG/ForkPoolWorker-1] content of the volume: [PosixPath('/sandcastle/README.md'), PosixPath('/sandcastle/Dockerfile'), PosixPath('/sandcastle/.git'), PosixPath('/sandcastle/.pre-commit-config.yaml'), PosixPath('/sandcastle/.gitattributes'), PosixPath('/sandcastle/setup.cfg'), PosixPath('/sandcastle/docs'), PosixPath('/sandcastle/files'), PosixPath('/sandcastle/packit.spec'), PosixPath('/sandcastle/ansible.cfg'), PosixPath('/sandcastle/.packit.yaml'), PosixPath('/sandcastle/Makefile'), PosixPath('/sandcastle/.gitignore'), PosixPath('/sandcastle/CHANGELOG.md'), PosixPath('/sandcastle/CONTRIBUTING.md'), PosixPath('/sandcastle/release-conf.yaml'), PosixPath('/sandcastle/recipe-tests.yaml'), PosixPath('/sandcastle/setup.py'), PosixPath('/sandcastle/packit'), PosixPath('/sandcastle/.zuul.yaml'), PosixPath('/sandcastle/fedora-tests'), PosixPath('/sandcastle/tests'), PosixPath('/sandcastle/Vagrantfile'), PosixPath('/sandcastle/LICENSE'), PosixPath('/sandcastle/.git_archival.txt')]
[2019-08-26 06:19:56,737: ERROR/ForkPoolWorker-1] Task task.steve_jobs.process_message[5adc02ce-9360-4854-a7fd-3e64c649c459] raised unexpected: PackitException("Command ['fedpkg', '--user', 'packit', '-q', 'clone', 'packit', '/tmp/packit-dist-gitbbtanuot'] failed: Command ['fedpkg', '--user', 'packit', '-q', 'clone', 'packit', '/tmp/packit-dist-gitbbtanuot'] failed.")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/tasks.py", line 42, in process_message
    return SteveJobs().process_message(event=event, topic=topic)
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 126, in process_message
    jobs_results = self.process_jobs(event_object)
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 92, in process_jobs
    handlers_results[job.job.value] = handler.run()
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/github_handlers.py", line 200, in run
    create_pr=False,
  File "/usr/local/lib/python3.7/site-packages/packit/api.py", line 164, in sync_release
    assert_existence(self.dg.local_project)
  File "/usr/local/lib/python3.7/site-packages/packit/distgit.py", line 98, in local_project
    anonymous=not cccolutils.has_creds(),
  File "/usr/local/lib/python3.7/site-packages/packit/fedpkg.py", line 91, in clone
    utils.run_command(cmd=cmd)
  File "/usr/local/lib/python3.7/site-packages/packit/utils.py", line 90, in run_command
    raise PackitException(f"Command {shell.args!r} failed: {error_message}")
packit.exceptions.PackitException: Command ['fedpkg', '--user', 'packit', '-q', 'clone', 'packit', '/tmp/packit-dist-gitbbtanuot'] failed: Command ['fedpkg', '--user', 'packit', '-q', 'clone', 'packit', '/tmp/packit-dist-gitbbtanuot'] failed.
[
```
Traceback from prod right now.

**Comment by TomasTomecek** [comment]
```
[2019-09-10 13:34:20,134: ERROR/ForkPoolWorker-1] No user exists for uid 1012120000                                                                                          
fatal: Could not read from remote repository.                                                                                                                                
                                                                                                                                                                             
Please make sure you have the correct access rights                                                                                                                          
and the repository exists.                                                            
Failed to set locale, defaulting to C.UTF-8                                                                                                                                  
Could not execute clone: Failed to execute command.
```

**Comment by rpitonak** [comment]
Could this be also the reason?
```
/usr/bin/run_worker.sh: line 9: /home/packit/passwd: Permission denied
```

**Comment by TomasTomecek** [comment]
nice catch, seems like that's the problem

**Comment by TomasTomecek** [comment]
I can't reproduce locally:
```
$ oc rsh pod/packit-worker-0

sh-5.0$ getent passwd packit
packit:x:1000140000:0:Packit Service:/home/packit:/bin/bash

sh-5.0$ kinit -k -t /secrets/fedora.keytab packit@FEDORAPROJECT.ORG

sh-5.0$ cd /tmp

sh-5.0$ fedpkg --user packit -q clone packit
The authenticity of host 'pkgs.fedoraproject.org (209.132.181.4)' can't be established.
RSA key fingerprint is SHA256:Q12OTyTeOHWlS54dTzy2BNu7wB8UKNf18+7WHIDsORc.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes 
Warning: Permanently added 'pkgs.fedoraproject.org,209.132.181.4' (RSA) to the list of known hosts.

sh-5.0$ ls -lha
total 4.0K
drwxrwxrwt. 1 root   root   20 Sep 16 12:30 .
drwxr-xr-x. 1 root   root   62 Sep 16 12:29 ..
-rwx------. 1 root   root 1.4K Aug 25 07:48 ks-script-_kvupbo7
drwxr-xr-x. 4 packit root  141 Sep 16 12:30 packit
```
