### ISSUE TITLE
worker/jobs.py", line 215: "TypeError: 'NoneType' object is not subscriptable"

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#95]
```
[2019-08-26 09:00:10,217: ERROR/ForkPoolWorker-1] Task task.steve_jobs.process_message[b77fdf10-cbc7-48ae-86c6-cc3e0f3ddec2] raised unexpected: TypeError("'NoneType' object is not subscriptable")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/tasks.py", line 42, in process_message
    return SteveJobs().process_message(event=event, topic=topic)
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 215, in process_message
    if any(not v["success"] for v in jobs_results.values()):
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 215, in <genexpr>
    if any(not v["success"] for v in jobs_results.values()):
TypeError: 'NoneType' object is not subscriptable
```

**Comment by jpopelka** [comment]
Looks like #61
